# -*- coding: utf-8 -*-
"""RoPE_vs_PoPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoAYm_14zeIWSvhguckhWttbJJJ7XXN7

# RoPE
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from datasets import load_dataset
import math

model_name = "timinar/baby-llama-58m"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model_pope = AutoModelForCausalLM.from_pretrained(model_name)

dataset = load_dataset("wikitext", "wikitext-2-raw-v1")


def tokenize(example):
    return tokenizer(example["text"], truncation=True, max_length=512)

tokenized = dataset.map(tokenize, batched=True, remove_columns=["text"])

def filter_empty(example):
    return len(example["input_ids"]) > 0

tokenized = tokenized.filter(filter_empty)

train = tokenized["train"]
val = tokenized["validation"]

from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

import csv
from transformers import TrainerCallback

class GPUStatsCallback(TrainerCallback):
    def __init__(self, filename="gpu_log.csv"):
        self.filename = filename

        with open(self.filename, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["step", "allocated_GB", "reserved_GB", "max_allocated_GB", "time"])

    def on_log(self, args, state, control, logs=None, **kwargs):
        if torch.cuda.is_available():
            allocated = torch.cuda.memory_allocated() / 1024**3
            reserved = torch.cuda.memory_reserved() / 1024**3
            max_allocated = torch.cuda.max_memory_allocated() / 1024**3

            with open(self.filename, "a", newline="") as f:
                writer = csv.writer(f)
                writer.writerow([
                    state.global_step,
                    allocated,
                    reserved,
                    max_allocated,
                    time.time()
                ])

"""#train rope"""

import time

training_args_rope = TrainingArguments(
    output_dir="./rope",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=32,

    per_device_eval_batch_size=1,

    max_steps=5000,

    num_train_epochs=2,
    logging_steps=50,
    save_steps=500,
)

trainer_rope = Trainer(
    model=model_rope,
    args=training_args_rope,
    train_dataset=train,
    eval_dataset=val,
    data_collator=data_collator,
    callbacks=[GPUStatsCallback()]
)

trainer_rope.train()

"""#перплексия"""

eval_rope = trainer_rope.evaluate()
ppl_rope = math.exp(eval_rope["eval_loss"])

print("RoPE perplexity:", ppl_rope)

print("Eval res rope:", eval_rope)

"""# mmlu"""

def format_question(model, example):
    question = example["question"]
    choices = example["choices"]

    prompt = question + "\n"
    for i, choice in enumerate(choices):
        prompt += f"{chr(65+i)}. {choice}\n"

    prompt += "Answer:"
    return prompt, example["answer"]

def get_answer(model, prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=5
        )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text


def evaluate_mmlu(model, dataset, n_samples=50):
    correct = 0

    for i in range(n_samples):
        prompt, label = format_question(model, dataset[i])
        output = get_answer(model, prompt)

        predicted = output.strip()[-1]  # последняя буква

        if predicted in ["A", "B", "C", "D"]:
            pred_idx = ord(predicted) - ord("A")
            if pred_idx == label:
                correct += 1

    acc = correct / n_samples
    print(f"Accuracy: {acc:.2f}")

    return acc

dataset = load_dataset("cais/mmlu", "abstract_algebra", split="test")

rope_acc = evaluate_mmlu(model_rope, dataset)

subjects = [
    "abstract_algebra",
    "high_school_physics",
    "computer_security",
    "astronomy",
    "philosophy",
    "high_school_computer_science",
    "college_mathematics",
    "machine_learning"
]

datasets_mmlu = {}

for subject in subjects:
    datasets_mmlu[subject] = load_dataset(
        "cais/mmlu",
        subject,
        split="test"
    )

sum_rope = 0

for subject, dataset in datasets_mmlu.items():
    print(f"\n=== {subject} ===")

    acc = evaluate_mmlu(model_rope, dataset)
    sum_rope += acc

    print("Accuracy:", acc)

print("Sum accurasy: ", sum_rope)

"""# niah

niah в зависимости от длины
"""

haystack = """
Machine learning is a branch of AI.
Transformers use attention mechanisms.
Neural networks process tensors.
""" * 200

needle = "The secret passcode is 8472."

context = insert_needle(
    haystack,
    needle,
    depth_percent=50
)

question = "What is the secret passcode?"

prompt = f"""
{context}

Question: {question}
Answer:
"""


inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=1024
).to(model_rope.device)

outputs = model_rope.generate(
    **inputs,
    max_new_tokens=20
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)


if "8472" in response:
    print("PASS")
else:
    print("FAIL")

context_lengths = [128, 256, 512, 1024]
depths = [10, 30, 50, 70, 90]


results = []

for context_len in context_lengths:

    truncated_haystack = haystack[:context_len * 5]

    for depth in depths:

        context = insert_needle(
            truncated_haystack,
            needle,
            depth
        )

        prompt = f"""
        {context}

        Question: What is the secret passcode?
        Answer:
        """

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=context_len
        ).to(model_rope.device)

        outputs = model_rope.generate(
            **inputs,
            max_new_tokens=20
        )

        response = tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

        passed = "8472" in response

        results.append({
            "context_length": context_len,
            "depth": depth,
            "success": int(passed)
        })

        print(context_len, depth, passed)




df = pd.DataFrame(results)

pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="success"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    cmap="RdYlGn"
)

plt.title("Needle In A Haystack")
plt.show()

needle = "The secret passcode is 8472."

question = "What is the secret passcode?"

# длинный текст
haystack = """
Machine learning is a branch of AI.
Transformers use attention mechanisms.
Neural networks process tensors.
Large language models use positional embeddings.
""" * 500

# параметры benchmark
context_lengths = [128, 256, 512, 1024]
depths = [10, 30, 50, 70, 90]

# сколько запусков на каждую комбинацию
n_runs = 5

results = []

for context_length in context_lengths:

    for depth in depths:

        successes = 0

        for run in range(n_runs):

            ok = run_niah_test(
                model_rope,
                tokenizer,
                context_length,
                depth
            )

            successes += int(ok)

            print(
                f"context={context_length} "
                f"depth={depth} "
                f"run={run+1} "
                f"success={ok}"
            )

        accuracy = successes / n_runs

        results.append({
            "context_length": context_length,
            "depth": depth,
            "accuracy": accuracy
        })

        print(
            f"FINAL -> context={context_length} "
            f"depth={depth} "
            f"accuracy={accuracy}"
        )

df = pd.DataFrame(results)

pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="accuracy"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    vmin=0,
    vmax=1
)

plt.title("Needle In A Haystack Accuracy")
plt.ylabel("Needle Depth (%)")
plt.xlabel("Context Length")

plt.show()

"""#lra"""

import torch

base_text = """
Transformers are neural architectures based on attention.
Large language models use positional embeddings.
Rotary Position Embedding improves positional encoding.
Polar Coordinate Positional Embedding is designed
for better long-context extrapolation.
""" * 400

facts = [
    ("The retrieval key is ALPHA-8472", "What is the retrieval key?", "ALPHA-8472"),
    ("The hidden city is Amsterdam", "What is the hidden city?", "Amsterdam"),
    ("The experiment year is 2025", "What is the experiment year?", "2025"),
]


context_lengths = [128, 256, 512, 1024]

depths = [10, 30, 50, 70, 90]

results = []

for context_length in context_lengths:

    for depth in depths:

        total = 0
        correct = 0

        for fact, question, answer in facts:

            ok, response = retrieval_test(
                model_rope,
                tokenizer,
                context_length,
                depth,
                fact,
                question,
                answer
            )

            total += 1
            correct += int(ok)

            print(
                f"context={context_length} "
                f"depth={depth} "
                f"question={question} "
                f"success={ok}"
            )

        accuracy = correct / total

        results.append({
            "context_length": context_length,
            "depth": depth,
            "accuracy": accuracy
        })

        print(
            f"FINAL: context={context_length} "
            f"depth={depth} "
            f"accuracy={accuracy}"
        )

df = pd.DataFrame(results)

pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="accuracy"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    vmin=0,
    vmax=1
)

plt.title("LRA-inspired Retrieval Benchmark")

plt.ylabel("Needle Depth (%)")
plt.xlabel("Context Length")

plt.show()

"""#PoPE"""

model_pope = AutoModelForCausalLM.from_pretrained(model_name)

import torch
from transformers.models.llama import modeling_llama

def rotate_half(x):
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)

def apply_pope(q, k, cos, sin, position_ids):

    if position_ids is None:
        position_ids = torch.arange(q.shape[-2], device=q.device).unsqueeze(0)

    pos = position_ids.float()

    r = torch.log(pos + 1).unsqueeze(-1)
    theta = pos / 10000

    cos = torch.cos(theta).unsqueeze(-1)
    sin = torch.sin(theta).unsqueeze(-1)

    q = r * (q * cos + rotate_half(q) * sin)
    k = r * (k * cos + rotate_half(k) * sin)

    return q, k

# original_apply_rope = modeling_llama.apply_rotary_pos_emb

def patched_apply_rotary_pos_emb(q, k, cos, sin, position_ids=None):
    return apply_pope(q, k, cos, sin, position_ids)

modeling_llama.apply_rotary_pos_emb = patched_apply_rotary_pos_emb

"""#train pope"""

training_args = TrainingArguments(
    output_dir="./pope",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=32,

    per_device_eval_batch_size=1,

    max_steps=5000,

    num_train_epochs=2,
    logging_steps=50,
    save_steps=500,
)


trainer_pope = Trainer(
    model=model_pope,
    args=training_args,
    train_dataset=train,
    eval_dataset=val,
    data_collator=data_collator,
    callbacks=[GPUStatsCallback()]
)

trainer_pope.save_model("./pope_final")
tokenizer.save_pretrained("./pope_final")

start = time.perf_counter()

trainer_pope.train()

end = time.perf_counter()

print((end-start)/60)

eval_pope = trainer_pope.evaluate()
ppl_pope = math.exp(eval_pope["eval_loss"])

print("RoPE perplexity:", ppl_pope)

print("Eval res pope:", eval_pope)

"""#mmlu"""

summ = 0

for subject, dataset in datasets_mmlu.items():
    print(f"\n=== {subject} ===")

    acc = evaluate_mmlu(model_pope, dataset)
    summ += acc

    print("Accuracy:", acc)

print("Sum accurasy: ", summ)

"""#niah"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

haystack = """
Machine learning is a branch of AI.
Transformers use attention mechanisms.
Neural networks process tensors.
""" * 200

needle = "The secret passcode is 8472."

def insert_needle(text, needle, depth_percent=50):
    words = text.split()

    insert_idx = int(len(words) * depth_percent / 100)

    words.insert(insert_idx, needle)

    return " ".join(words)

context = insert_needle(
    haystack,
    needle,
    depth_percent=50
)

question = "What is the secret passcode?"

prompt = f"""
{context}

Question: {question}
Answer:
"""


inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=1024
).to(model_pope.device)

outputs = model_pope.generate(
    **inputs,
    max_new_tokens=20
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)


if "8472" in response:
    print("PASS")
else:
    print("FAIL")

context_lengths = [128, 256, 512, 1024]
depths = [10, 30, 50, 70, 90]


results = []

for context_len in context_lengths:

    truncated_haystack = haystack[:context_len * 5]

    for depth in depths:

        context = insert_needle(
            truncated_haystack,
            needle,
            depth
        )

        prompt = f"""
        {context}

        Question: What is the secret passcode?
        Answer:
        """

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=context_len
        ).to(model_pope.device)

        outputs = model_pope.generate(
            **inputs,
            max_new_tokens=20
        )

        response = tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

        passed = "8472" in response

        results.append({
            "context_length": context_len,
            "depth": depth,
            "success": int(passed)
        })

        print(context_len, depth, passed)




df = pd.DataFrame(results)

pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="success"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    cmap="RdYlGn"
)

plt.title("Needle In A Haystack")
plt.show()

"""niah в зависимости от длины"""

import random

needle = "The secret passcode is 8472."

question = "What is the secret passcode?"

# длинный текст
haystack = """
Machine learning is a branch of AI.
Transformers use attention mechanisms.
Neural networks process tensors.
Large language models use positional embeddings.
""" * 500


def run_niah_test(model, tokenizer, context_length, depth,):
    # обрезаем текст под нужный контекст
    truncated = haystack[:context_length * 5]

    context = insert_needle(
        truncated,
        needle,
        depth
    )

    prompt = f"""
    {context}

    Question: {question}
    Answer:
    """

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=context_length
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=10,
        do_sample=False
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    success = "8472" in response

    return success


# параметры benchmark
context_lengths = [128, 256, 512, 1024]
depths = [10, 30, 50, 70, 90]

# сколько запусков на каждую комбинацию
n_runs = 5

results = []

for context_length in context_lengths:

    for depth in depths:

        successes = 0

        for run in range(n_runs):

            ok = run_niah_test(
                model_pope,
                tokenizer,
                context_length,
                depth
            )

            successes += int(ok)

            print(
                f"context={context_length} "
                f"depth={depth} "
                f"run={run+1} "
                f"success={ok}"
            )

        accuracy = successes / n_runs

        results.append({
            "context_length": context_length,
            "depth": depth,
            "accuracy": accuracy
        })

        print(
            f"FINAL -> context={context_length} "
            f"depth={depth} "
            f"accuracy={accuracy}"
        )

# dataframe
df = pd.DataFrame(results)

print(df)

# heatmap
pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="accuracy"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    vmin=0,
    vmax=1
)

plt.title("Needle In A Haystack Accuracy")
plt.ylabel("Needle Depth (%)")
plt.xlabel("Context Length")

plt.show()

"""#LRA"""

import torch

base_text = """
Transformers are neural architectures based on attention.
Large language models use positional embeddings.
Rotary Position Embedding improves positional encoding.
Polar Coordinate Positional Embedding is designed
for better long-context extrapolation.
""" * 400

facts = [
    ("The retrieval key is ALPHA-8472", "What is the retrieval key?", "ALPHA-8472"),
    ("The hidden city is Amsterdam", "What is the hidden city?", "Amsterdam"),
    ("The experiment year is 2025", "What is the experiment year?", "2025"),
]


def insert_fact(text, fact, depth_percent):

    words = text.split()

    idx = int(len(words) * depth_percent / 100)

    words.insert(idx, fact)

    return " ".join(words)



def retrieval_test(
    model,
    tokenizer,
    context_length,
    depth,
    fact,
    question,
    answer,
):

    context = insert_fact(
        base_text[:context_length * 5],
        fact,
        depth
    )

    prompt = f"""
    {context}

    Question: {question}

    Answer:
    """

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=context_length
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=10,
        do_sample=False
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    success = answer.lower() in response.lower()

    return success, response


context_lengths = [128, 256, 512, 1024]

depths = [10, 30, 50, 70, 90]

results = []

for context_length in context_lengths:

    for depth in depths:

        total = 0
        correct = 0

        for fact, question, answer in facts:

            ok, response = retrieval_test(
                model_pope,
                tokenizer,
                context_length,
                depth,
                fact,
                question,
                answer
            )

            total += 1
            correct += int(ok)

            print(
                f"context={context_length} "
                f"depth={depth} "
                f"question={question} "
                f"success={ok}"
            )

        accuracy = correct / total

        results.append({
            "context_length": context_length,
            "depth": depth,
            "accuracy": accuracy
        })

        print(
            f"FINAL: context={context_length} "
            f"depth={depth} "
            f"accuracy={accuracy}"
        )

df = pd.DataFrame(results)

pivot = df.pivot(
    index="depth",
    columns="context_length",
    values="accuracy"
)

plt.figure(figsize=(8,6))

sns.heatmap(
    pivot,
    annot=True,
    vmin=0,
    vmax=1
)

plt.title("LRA-inspired Retrieval Benchmark")

plt.ylabel("Needle Depth (%)")
plt.xlabel("Context Length")

plt.show()